# Generated by Django 4.0.3 on 2022-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('language', models.CharField(default="O'zbek tilida", max_length=50)),
                ('released_year', models.IntegerField(null=True)),
                ('duration', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('source_link', models.URLField()),
                ('banner', models.ImageField(null=True, upload_to='banners')),
                ('views_count', models.IntegerField(default=0)),
                ('category_id', models.IntegerField(null=True)),
                ('created_add', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=250)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('MOVIE', 'MOVIE'), ('TRAILER', 'TRAILER'), ('SHOW', 'SHOW'), ('SERIES', 'SERIES')], default='MOVIE', max_length=7)),
            ],
        ),
    ]
